server: 
  port: 8326
info:
  contact: 
    email: dimei1@creditharmony.cn
logging: 
  file: common-microservice-monitor-system-8326.log
  level:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: INFO
# Spring boot UI 页面关闭该应用的权限限制
management: 
  security: 
    enabled: true
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eurekaserver:8888/eureka/

#数据源：
spring:
  datasource:
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa: 
    show-sql: false
    hibernate: 
        ddl-auto: update
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
    properties:  
      hibernate:  
#       dialect: com.microservice.persistence.SRDB10Dialect
        dialect: ${datasource.jdbc.dialect}
#       dialect: org.hibernate.dialect.MySQLDialect
        temp: 
          use_jdbc_metadata_defaults: false
  mail:
    protocol: smtp
    host: mail.creditharmony.cn
    port: 25
    auth: true
    username: XH\linansun
    password: sunlinan66**
#涉及接口调用的超时时间
feign: 
  hystrix:
    enabled: false
  client: 
    config: 
      default: 
        connectTimeout: 20000
        readTimeout: 20000
  compression:
    request: true
    response: true    
