server: 
  port: 5011
info:
  contact: 
    email: dimei1@creditharmony.cn
logging: 
  file: common-microservice-insurance-yangzhou-9001.log
  level:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: INFO
# Spring boot UI 页面关闭该应用的权限限制
management: 
  security: 
    enabled: false
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eurekaserver:8888/eureka/



#数据源：
spring:
  datasource:
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
#    type: com.zaxxer.hikari.HikariDataSource
  jpa: 
#    show-sql: true
    hibernate: 
        ddl-auto: update
        naming: 
          strategy : org.hibernate.cfg.ImprovedNamingStrategy  
    properties:  
      hibernate:  
#       dialect: com.microservice.persistence.SRDB10Dialect
        dialect: ${datasource.jdbc.dialect}
#       dialect: org.hibernate.dialect.MySQLDialect
          

