server: 
  port: 12138
info:
  contact: 
    email: dimei1@creditharmony.cn
logging: 
  file: common-microservice-housingfund-jingzhou.log
  level:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: INFO
# Spring boot UI 页面关闭该应用的权限限制

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eurekaserver:8888/eureka/


#数据源：
spring:
  cloud:
    stream:
      bindings:
        carrier_channel:
          binder: housingfund_binder
      binders:
        carrier_binder: 
          type: kafka 
          environment:
            spring.cloud.stream.kafka.binder.brokers: ${kafka.brokers}
            spring.cloud.stream.kafka.binder.zk-nodes: ${kafka.zknodes} 
            
            
  datasource:
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
#    type: com.zaxxer.hikari.HikariDataSource
  jpa: 
#    show-sql: true
    hibernate: 
        ddl-auto: update
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl  
    properties:  
      hibernate:  
#       dialect: com.microservice.persistence.SRDB10Dialect
        dialect: ${datasource.jdbc.dialect}
        temp: 
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法为实现
#       dialect: org.hibernate.dialect.MySQLDialect

