server: 
  port: 8322
info:
  contact: 
    email: dimei1@creditharmony.cn
logging: 
  file: common-microservice-middle-8322.log
  level:  
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: INFO
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://eurekaserver:8888/eureka/

#数据源：
spring:
  datasource:
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa:
    show-sql: false
    hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: ${datasource.jdbc.dialect}
        temp:
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法为实现
feign: 
  hystrix:
    enabled: false
  client: 
    config: 
      default: 
        connectTimeout: 100000
        readTimeout: 100000
  compression:
    request: true
    response: true        

