server: 
  port: 1212
logging:
  file: common-microservice-mobile-etl-1212.log
  level: 
    com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter : OFF
    com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject : OFF
    com.gargoylesoftware.htmlunit.host.html.HTMLDocument : OFF
    com.gargoylesoftware.htmlunit.html.HtmlScript : OFF
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8888/eureka/


#数据源：
spring:
  thymeleaf: 
    cache : ${spring.thymeleaf.cache}
  cloud: 
    stream:
      bindings: 
        input:                             # 频道名称（根据具体模块来命名）
          destination: carrier-topic-01                   
          group: etl_group             # 消费者组订阅是持久的，如果你的应用指定了group，那即便你这个组下的所有应用实例都挂掉了，你的应用也会在重新启动后从未读取过的位置继续读取
          binder: kafka_binder
      binders: 
        kafka_binder: 
          type: kafka 
          environment:
            spring.cloud.stream.kafka.binder.brokers: ${kafka.brokers}
            spring.cloud.stream.kafka.binder.zk-nodes: ${kafka.zknodes} 
  datasource:
    data: 
      - ${datasource.data}  # spring.datasource.data 执行晚于jpa ， 适用于字典表数据的初始化
      - ${datasource.schema} 
    initialization-mode: ${datasource.initialization-mode} 
    continueOnError: false
    separator: ;;
    schema-username: ${datasource.jdbc.username}
    schema-password: ${datasource.jdbc.password}
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa: 
    show-sql: false
    hibernate: 
        ddl-auto: update 
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
          
    properties:  
      hibernate:  
        dialect: ${datasource.jdbc.dialect}
        temp: 
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法为实现

          

