server: 
  port: 1216
logging:
  file: common-microservice-housingfund-etl-1213.log
  level: 
    com.gargoylesoftware.htmlunit.javascript.StrictErrorReporter : OFF
    com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject : OFF
    com.gargoylesoftware.htmlunit.host.html.HTMLDocument : OFF
    com.gargoylesoftware.htmlunit.html.HtmlScript : OFF
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8888/eureka/

feign: 
  hystrix:
    enabled: false
  client: 
    config: 
      default: 
        connectTimeout: 100000
        readTimeout: 100000 
#数据源：
spring:
  cloud:
    stream:
      bindings:
        input:                                 # 频道名称（根据具体模块来命名）
          destination: housingfund-topic-01 
          group: etl_group
          binder: kafka_binder
      binders:
        kafka_binder: 
          type: kafka 
          environment:
            spring.cloud.stream.kafka.binder.brokers: ${kafka.brokers}
            spring.cloud.stream.kafka.binder.zk-nodes: ${kafka.zknodes}
  datasource:
    hikari: 
      minimum-idle: ${datasource.jdbc.minIdle}
      maximum-pool-size: ${datasource.jdbc.maxPoolSize}
    driver-class-name: ${datasource.jdbc.driver}
    url: ${datasource.jdbc.url}
    username: ${datasource.jdbc.username}
    password: ${datasource.jdbc.password}
    type: ${datasource.jdbc.type}
  jpa: 
    show-sql: false
    hibernate: 
        ddl-auto: update 
        naming: 
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl 
    properties:  
      hibernate:   
        dialect: ${datasource.jdbc.dialect} 
        temp: 
          use_jdbc_metadata_defaults: false #此处是为了解决启动时报错createClob()方法为实现
          
          

